spring:
  config:
    activate:
      on-profile: prod

  jpa:
    show-sql: false


logging:
  level:
    org.hibernate.SQL: !!str info

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health