spring:
  config:
    activate:
      on-profile: dev

logging:
  level:
    root: info
    org.hibernate.SQL: !!str debug

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,metrics